# Generated by Django 4.1.4 on 2022-12-29 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_share', '0003_recipe_recipe_pic_recipe_time_to_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
